# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: algamoney
      POSTGRES_PASSWORD: algamoney
      POSTGRES_DB: algamoney
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"